export const demoData = {
  currentUser: {
    name: "Christoph Schernthaner",
    username: "christoph",
    workspace: "saniPEP Sanitätshaus GmbH & Co. KG",
    environment: "Lokales BFF / Demo-Daten",
  },
  cases: [
    {
      id: "sp-18581",
      number: "18581",
      customer: "Max Mustermann",
      payer: "AOK Bayern",
      status: "Neu",
      branch: "saniPEP Sanitätshaus",
      article: "VLIESKOMPRESSEN unsteril 10x10 cm",
      total: "18,50 EUR",
    },
    {
      id: "sp-18542",
      number: "18542",
      customer: "Erika Beispiel",
      payer: "IKK classic",
      status: "Abholbereit",
      branch: "Filiale Mitte",
      article: "Bandage Standard",
      total: "42,20 EUR",
    },
  ],
  orderProposals: [
    {
      id: "op-413",
      article: "VLIESKOMPRESSEN unsteril 10x10 cm",
      customer: "Max Mustermann",
      supplier: "MedComplett GmbH",
      quantity: 5,
      unit: "Packung",
      value: "92,50 EUR",
      state: "Vorschlag",
    },
    {
      id: "op-414",
      article: "Bandage Standard",
      customer: "Erika Beispiel",
      supplier: "Orthomed Lieferant",
      quantity: 1,
      unit: "Stück",
      value: "31,70 EUR",
      state: "Prüfen",
    },
  ],
  orders: [
    {
      id: "order-413",
      number: "413",
      supplier: "MedComplett GmbH",
      status: "Erstellt",
      orderValue: "92,50 EUR",
      documentState: "Bestelldokument bereit",
      mailState: "PDF/Mail vorbereitet",
    },
    {
      id: "order-411",
      number: "411",
      supplier: "RehaLogistik",
      status: "Offen",
      orderValue: "120,00 EUR",
      documentState: "Entwurf",
      mailState: "Nicht vorbereitet",
    },
  ],
  goodsReceipts: [
    {
      id: "gr-413",
      orderNumber: "413",
      supplier: "MedComplett GmbH",
      article: "VLIESKOMPRESSEN unsteril 10x10 cm",
      quantity: 5,
      remainingQuantity: 5,
      storageLocation: "Hauptlager",
      status: "Offen",
    },
  ],
  auditSeed: [
    {
      id: "audit-1",
      time: "00:46:18",
      actor: "Christoph Schernthaner",
      module: "Bestellung",
      action: "Bestellvorschlag in Bestellung umgewandelt",
      target: "Bestellung 413",
      status: "ok",
    },
    {
      id: "audit-2",
      time: "00:48:02",
      actor: "Christoph Schernthaner",
      module: "Wareneingang",
      action: "Wareneingang erfasst",
      target: "Bestellung 413",
      status: "ok",
    },
  ],
  procurementCases: [
    {
      id: "proc-case-18581",
      salesProcessId: "sp-18581",
      number: "18581",
      status: "Bestellvorschlag",
      customer: {
        id: "cust-max",
        firstName: "Max",
        lastName: "Mustermann",
        displayName: "Max Mustermann",
        customerNumber: "10042",
        dateOfBirth: "1980-04-12",
        insuranceNumber: "A123456789",
      },
      deliveryAddress: {
        street: "Musterweg",
        houseNumber: "12",
        zipCode: "80331",
        city: "Musterstadt",
        country: "DE",
      },
      proposals: [
        {
          id: "proposal-18581-1",
          salesProcessId: "sp-18581",
          supplierId: "supplier-medcomplett",
          supplierName: "MedComplett GmbH",
          articleId: "article-10001",
          articleNumber: "ART-10001",
          pzn: "",
          description: "VLIESKOMPRESSEN unsteril 10x10 cm",
          quantity: 5,
          unit: "Packung",
          value: "92,50 EUR",
        },
        {
          id: "proposal-18581-2",
          salesProcessId: "sp-18581",
          supplierId: "supplier-orthomed",
          supplierName: "Orthomed Lieferant",
          articleId: "article-20002",
          articleNumber: "ART-20002",
          pzn: "87654321",
          description: "Bandage Standard",
          quantity: 1,
          unit: "Stück",
          value: "31,70 EUR",
        },
      ],
    },
    {
      id: "proc-case-18542",
      salesProcessId: "sp-18542",
      number: "18542",
      status: "Bestellvorschlag",
      customer: {
        id: "cust-erika",
        firstName: "Erika",
        lastName: "Beispiel",
        displayName: "Erika Beispiel",
        customerNumber: "10043",
        dateOfBirth: "1974-10-03",
        insuranceNumber: "B987654321",
      },
      deliveryAddress: {
        street: "Filialstraße",
        houseNumber: "4",
        zipCode: "80333",
        city: "München",
        country: "DE",
      },
      proposals: [
        {
          id: "proposal-18542-1",
          salesProcessId: "sp-18542",
          supplierId: "supplier-medcomplett",
          supplierName: "MedComplett GmbH",
          articleId: "article-30003",
          articleNumber: "ART-30003",
          pzn: "",
          description: "Fixierbinde elastisch 8 cm",
          quantity: 3,
          unit: "Packung",
          value: "24,90 EUR",
        },
      ],
    },
  ],
  articleDetailsById: {
    "article-10001": {
      pzn: "12345678",
      articleNumber: "ART-10001",
      description: "VLIESKOMPRESSEN unsteril 10x10 cm",
    },
    "article-20002": {
      pzn: "87654321",
      articleNumber: "ART-20002",
      description: "Bandage Standard",
    },
  },
};
