[Port]
; Gibt die Nummer des gewünschten COM-Ports für serielle Anschlüsse an.
; Ist zusätzlich eine IPAddress in der Config definiert, so wird der ComPort ignoriert
ComPort=3

; LAN oder WLAN-Verbindungen wird hier die IPAdresse des Kartenterminals definiert. Hierzu muss zwingend auch ein Port mit IPPort definiert werden.
IPAddress=

; IP-Port für die o.g. IP-Adresse des Kartenterminals.
; Bei Verifone wurde 22000, bei Ingenico 5577 und bei CCV der Port 20007 als Default verwendet.
IPPort=

[Haendler]
; ZVT-Passwort zur internen Kommunikation mit dem Kartenterminal.
; Hier ist typischerweise bei allen Terminals auch intern als Default "000000" gesetzt.
Passwort1=000000

[Logging]
; Definiert man den Key mit "LogDebug=1", so kann damit ein erweitertes Logging zur Fehlersuche und Entwicklung aktiviert werden.
; Siehe auch Kapitel: Logging
; Der ältere Keyname "Trace" der evtl. ähnliches bewirkt wurde hier bewusst nicht übernommen um viell. alte vergessene Log-Aktivierungen nicht weiter zu übernehmen.
LogDebug=0
